[tool.poetry]
name = "hyperparameter_optimization"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
networkx = {extras = ["default"], version = "^2.8.8"}
matplotlib = "^3.5.2"
maturin = "^0.13.0"
optuna = "^2.10.1"
numpy = "^1.23.1"
sklearn = "^0.0"
optuna-dashboard = "^0.7.3"
tulip-python = "^5.6.3"
pillow = "^9.4.0"
statsmodels = "^0.13.5"
seaborn = "^0.12.2"

[tool.poetry.dev-dependencies]
ipykernel = "^6.15.1"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
isort = "^5.11.3"
flake8 = "^6.0.0"
pyproject-flake8 = "^6.0.0.post1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
import_heading_stdlib      = "Standard Library"
import_heading_thirdparty  = "Third Party Library"
import_heading_firstparty  = "First Party Library"
import_heading_localfolder = "Local Library"
multi_line_output = 3
include_trailing_comma = true
known_firstparty = ['quality_metrics', 'utils', 'drawing']

[tool.flake8]
max-line-length = 79
exclude = [".venv", ".git", "__pycache__",]
max-complexity = 10
