[tool.poetry]
name = "hyperparameter_optimization"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
networkx = "^2.8.4"
matplotlib = "^3.5.2"
maturin = "^0.13.0"
optuna = "^2.10.1"
numpy = "^1.23.1"

[tool.poetry.dev-dependencies]
ipykernel = "^6.15.1"
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
